version: '3'

services:

  nodejs:
    container_name: nodejs
    build: '.'
    entrypoint: ["./init.sh"]
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - mongo

    networks:
      - app-connect
    ports:
      - '3333:3333'

  mongo:
    container_name: mongo
    image: 'mongo'
    restart: always
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect





volumes:
  mongo-data:



networks:
  app-connect:
      driver: bridge
